# LIST OF REQUIRED PACKAGES ----

library(sparklyr)
library(dplyr)
library(corrr)
library(shiny)
library(shinycssloaders)
library(shinyjs)
library(shinyWidgets)
library(ggplot2)
library(leaflet)
library(plotly)
library(arrow)
library(purrr)
library(reshape2)
library(DT)
library(here)
library(rlang)
library(bslib)